/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ApigardenGroups {
    'ageFrom'?: number;
    'ageTo'?: number;
    'childrenCount'?: number;
    'id'?: number;
    'label'?: string;
    'type'?: ApigardenGroups.TypeEnum;
}

export namespace ApigardenGroups {
    export enum TypeEnum {
        SPEECH = 'SPEECH',
        SPECIAL = 'SPECIAL',
        SMALL = 'SMALL',
        ALLERGY = 'ALLERGY',
        NORMAL = 'NORMAL'
    }
}
