/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Garden {
    'address': string;
    'buildDate': Date;
    'buildingStateInfo'?: models.ApigardenBuildingStateInfo;
    'elderate': string;
    'email'?: string;
    'groups'?: Array<models.ApigardenGroups>;
    'id': number;
    'idFromSource': number;
    'label': string;
    'missedDaysInfo'?: models.ApigardenMissedDaysInfo;
    'phone'?: string;
    'schoolNo'?: number;
    'schoolType': string;
    'www'?: string;
}
